version: "3.9"
services:
  frontend:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /code/node_modules
      - ./frontend:/code
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
